### ISSUE TITLE
Error executing statement "Unknown column modTemplate.name" during package installation.

### ISSUE THREAD

**Issue by alexxx-ivanow** [azernov/modxbuilder#1]
### Проблема
В процессе установки собранного при помощи modxbuilder пакета в логах появляется ошибка:

![nI7YPWER](https://user-images.githubusercontent.com/17097374/99039493-7bf76680-2598-11eb-9902-3c868c2f30ab.jpg)

 не найдено поле modTemplate.name. 
### Воспроизведение

Собрать и установить пакет, в котором есть шаблоны

### Решение
В классе modxbuilder.class.php, в методе addTemplatesToCategory:

`public function addTemplatesToCategory(&$category,$templates,&$attr,$updateObject = true){
        $attr[xPDOTransport::RELATED_OBJECT_ATTRIBUTES]['Templates'] = array(
            xPDOTransport::PRESERVE_KEYS => true,
            xPDOTransport::UPDATE_OBJECT => $updateObject,
            xPDOTransport::UNIQUE_KEY => 'name',
        );
        return $category->addMany($templates);
    }`
строку ` xPDOTransport::UNIQUE_KEY => 'name',` поменял на ` xPDOTransport::UNIQUE_KEY => 'templatename',`

### Резюме
По факту, шаблон всё равно устанавливался из пакета. Но при смене уникального поля на "templatename" лог установки перестает выдавать ошибку.

**Comment by azernov** [comment]
Благодарю за найденный баг.
Исправил!
